Repository k3ai/k3ai, pull requests merged in 2021-11, with the labels that each got.

#2 [Core] - Initial work for v3 version
  .github/config.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  cmd/cluster.go
  cmd/down.go
  cmd/plugin.go
  cmd/root.go
  cmd/run.go
  cmd/up.go
  cmd/version.go
  config/config.go
  go.mod
  go.sum
  internal/deployments/deployment.yaml
  internal/names/names.go
  internal/variables.go
  log/log.go
  main.go
  pkg/auth/gh.go
  pkg/color/color.go
  pkg/db/db.go
  pkg/env/config.go
  pkg/http/http.go
  pkg/io/execution/factory.go
  pkg/io/files/files.go
  pkg/io/git/git.go
  pkg/loader/loader.go
  pkg/runner/run.go
  pkg/tables/tables.go
  version/version.go
Labels: done

#21 [Cherry Picking] - Fix typos plus wait command
  README.md
  install.sh
  pkg/io/execution/factory.go
  pkg/runner/run.go
Labels: bug

#30 Add config support to k3ai
  .gitignore
  cmd/cluster.go
  cmd/plugin.go
  cmd/run.go
  internal/variables.go
  pkg/runner/run.go
Labels: epic, done

#36 [Feature] - Running Kubeflow and MLFLow code through "One-Click" approach
  cmd/run.go
  internal/variables.go
  pkg/db/db.go
  pkg/io/execution/factory.go
  pkg/runner/run.go
Labels: in progress, todo :spiral_notepad:

#39 [Feature] - Civo Integration
  internal/variables.go
  pkg/env/config.go
  pkg/infra/infrastructure.go
  pkg/io/execution/factory.go
Labels: in progress, todo :spiral_notepad:
